#!/bin/sh
#inkVerbSerf! verb.ink

# This adds domains with OpenDKIM profiles and keys and inkCert and Apache configs and enables CGI.
## This also creates a folder for the domain in www/domains which an ftpvip can access

# How to use:
## ./adddomaincgi [newdomain.tld]


# Include settings
. /opt/verb/conf/sitenameip
. /opt/verb/conf/inkcert/inkcertstatus

NEWDOMAIN=$1

# Check the domain shell
if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN} ]; then
/bin/echo "The shell for ${NEWDOMAIN} does not exist yet. Creating it..."
/opt/verb/serfs/newdomainshell ${NEWDOMAIN}
fi

# Check if it already exists
if [ -f /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf ]; then
 if [ -f /etc/httpd/sites-enabled/${NEWDOMAIN}.conf ]; then
 /bin/echo "That subdomain already exists."
 exit 0
 else
 /bin/echo "That site's config exists, but it doesn't seem to be active on Apache. Something's not right."
 exit 0
 fi
fi

# Copy and prepare Apache server config files
/bin/cp /opt/verb/conf/site-files/conf/newdomaincgi.tld.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
/bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
if [ ! -d /srv/www/domains/${NEWDOMAIN} ]; then
/bin/cp -rf /opt/verb/conf/site-files/newdomain.tld /srv/www/domains/${NEWDOMAIN}
fi
/bin/ln -sfn /srv/www/domains/${NEWDOMAIN} /srv/www/html/
/bin/chown -R www:www /srv/www/html/${NEWDOMAIN}
/bin/chown -R www:www /srv/www/domains/${NEWDOMAIN}
/bin/chmod -R 750 /srv/www/domains/${NEWDOMAIN}
/opt/verb/serfs/nginxensite ${NEWDOMAIN}
/usr/sbin/apache2ctl graceful
## Just in case...
/bin/systemctl start apache2

# inkCert
## Ensure that you don't get double entries
/bin/sed -i "s/, ${NEWDOMAIN}/ /g" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
## Add it to the cli-ini
/bin/sed -i "/^domains =/ s/$/, ${NEWDOMAIN}/" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini

# Finish
/bin/echo "Great! With no error messages, you are ready to run inkCert for ${NEWDOMAIN}, unless you want to add subdomains."
