#!/bin/sh
#inkVerbSerf! verb.ink

# This enables an nginx site by creating a symlink.

# How to use:
## ./ensitenginx [domain.tld or subdomain.domain.tld]


# Run as a loop so multiple sites can be enabled in one command, just like a2ensite
for DOMAIN in $@
do

  /usr/bin/ln -sfn /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf /opt/verb/conf/webserver/nginx/sites-enabled/${DOMAIN}.conf

done

# Reload
/usr/bin/systemctl reload nginx
