#!/bin/sh
#inkVerbSerf! verb.ink

# This removes the wildcard * subdomain wildcard

# How to use:
## ./fixwildrm [domain.tld or subdomain.domain.tld]


DOMAIN=$1


# Verify that the "fixwildcard" has been added
if ! /bin/grep -q "INKWILDFIX=fixed" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf; then
	/bin/echo "${DOMAIN} doesn't have the wildcard subdomain fix. Nothing to do."
else

# Remove the old settings
/bin/sed -i "/ServerAlias *.${DOMAIN}/d" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
/bin/sed -i '/##INKWILDFIX/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf

/usr/sbin/apache2ctl graceful
/bin/echo "${DOMAIN} the wildcard subdomain fix has been removed."
