#!/bin/sh
#inkVerbSerf! verb.ink

# This installs Bind DNS for managing DNS records in the inkDNS zone file on this Verber
## This makes the server itself tha authoritative DNS server with a default/optional backup serfer
## If the backup server is not specified, the default will be used, which should be used unless this is a domain mod

# How to use:
## ./inkdnsinstall [ns domain - optional]

# Eg:
## ./inkdnsinstall
## ./inkdnsinstall ns3.inkisaverb.com
## ./inkdnsinstall ns.poetryiscode.com


# Check if installed
. /opt/verb/conf/inkdns/inkdnsconf
if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
  /bin/echo "inkDNS already installed."
  exit 0
fi

# Set the Inkers
/opt/verb/serfs/inkdnssetinker
/opt/verb/serfs/inkdnssetinker

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Install Bind
/usr/bin/pacman -S --noconfirm bind

# Config
/bin/cp -f /etc/named.conf /etc/named.conf.original
/bin/cp -f /opt/verb/conf/inkdns/named.conf /etc/
/bin/chown bind:bind /etc/named.conf
/bin/chmod 644 /etc/named.conf
## Make sure our included files exist
/usr/bin/touch /opt/verb/conf/inkdns/named.conf.rdns
/usr/bin/touch /opt/verb/conf/inkdns/named.conf.verb

# Set the NS domains
/bin/sed -i "s/ns1\.DNSDOMAIN286/${hostURI}/g" /opt/verb/conf/inkdns/zones/*
/bin/sed -i "s/ns1\.DNSDOMAIN286/${hostURI}/g" /opt/verb/conf/inkdns/*
/bin/sed -i "s/ns2\.DNSDOMAIN286/${SITEINKERDNS}/g" /opt/verb/conf/inkdns/inkzones/*
/bin/sed -i "s/ns2\.DNSDOMAIN286/${SITEINKERDNS}/g" /opt/verb/conf/inkdns/zones/*
/bin/sed -i "s/ns2\.DNSDOMAIN286/${SITEINKERDNS}/g" /opt/verb/conf/inkdns/*
/bin/sed -i "s/ns3\.DNSDOMAIN286/${SITE2INKERDNS}/g" /opt/verb/conf/inkdns/inkzones/*
/bin/sed -i "s/ns3\.DNSDOMAIN286/${SITE2INKERDNS}/g" /opt/verb/conf/inkdns/zones/*
/bin/sed -i "s/ns3\.DNSDOMAIN286/${SITE2INKERDNS}/g" /opt/verb/conf/inkdns/*

## DEV: FYI apparmor permissions are here: /etc/apparmor.d/usr.sbin.named

# DNS serial number
/bin/echo '0 0 * * * root /opt/verb/donjon/rmserial.sh > /dev/null 2>&1' > /etc/cron.d/dnsserial
/bin/chmod 0644 /etc/cron.d/dnsserial
/bin/echo '#!/bin/sh
/bin/rm -f /opt/verb/conf/inkdns/serial' > /opt/verb/donjon/rmserial.sh
/bin/chmod 750 /opt/verb/donjon/rmserial.sh

# Allow the port
/usr/bin/ufw allow 53

# Restart
/bin/systemctl enable named
/bin/systemctl start named

# Config
/bin/sed -i "s/INKDNSSTAT=.*/INKDNSSTAT=\"INSTALLED\"/" /opt/verb/conf/inkdns/inkdnsconf

# Refresh all records
/opt/verb/serfs/inkdnsrefreshbind

# Finish
/bin/echo "inkDNS installed."
