#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new subdomain to become newsub.your-name.verb.one, and enables CGI.

# How to use:
## ./newonesubcgi [newsub only]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWONESUB=$1

# Copy and prepare Apache server config files
/bin/cp /opt/verb/conf/site-files/conf/newonesubcgi.conf /etc/apache2/sites-available/${NEWONESUB}.${oneURI}.conf 
/bin/sed -i "s/newonesub/${NEWONESUB}/g" /etc/apache2/sites-available/${NEWONESUB}.${oneURI}.conf
/bin/sed -i "s/oneURI286/${oneURI}/g" /etc/apache2/sites-available/${NEWONESUB}.${oneURI}.conf
/bin/cp -R /opt/verb/conf/site-files/newonesubdir /srv/www/one/${NEWONESUB}
/bin/chown -R www:www /srv/www/one/${NEWONESUB}
/opt/verb/serfs/nginxensite ${NEWONESUB}.${oneURI}
/usr/sbin/apache2ctl graceful
/bin/cp /srv/www/html/one/index-newonesub.php /srv/www/html/one/index-${NEWONESUB}.php
/bin/chown -R www:www /srv/www/html/one

# inkCert, at end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, ${NEWONESUB}.${oneURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${oneURI}.ini

