#!/bin/sh
#inkVerbSerf! verb.ink

# This copies all original verb folders to www/html if they don't exist
## This is used by killvapp and others
## This is used by make-verber
## This does not change ownership of folders to www-data, which must be done separately on a production server.

# How to use:
## ./updatehtmlverbs


# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Make the commute to where we will work
cd /srv/www/html

# Remove broken links
/usr/bin/find -L . -name . -o -type d -prune -o -type l -exec rm {} +

# Initial sites
/bin/rm -rf 0sitedefaultInProgress
/bin/cp -r /opt/verb/conf/lab/html/0sitedefaultInProgress .
/bin/chmod -R 750 0sitedefaultInProgress
/bin/rm -rf vsslsitedefault
/bin/cp -r 0sitedefaultInProgress vsslsitedefault
/bin/rm -rf 0ne
/bin/mkdir 0ne
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /srv/www/html/0ne/index.php
/bin/chmod -R 750 0ne

# Block web folder listing
/bin/echo "Options -Indexes" >> /srv/www/html/.htaccess
/bin/echo "Options -Indexes" >> /srv/www/html/0ne/.htaccess
/bin/echo "Options -Indexes" >> /srv/www/html/0sitedefaultInProgress/.htaccess

# Verb sites
if [ ! -e ink ]; then
  /bin/cp -r 0sitedefaultInProgress ink
fi
if [ ! -e email ]; then
  /bin/cp -r 0ne email
fi
if [ ! -e one ]; then
  /bin/cp -r 0ne one
fi
if [ ! -e blue ]; then
  /bin/cp -r 0ne blue
fi
if [ ! -e vip ]; then
  /bin/cp -r 0ne vip
fi
if [ ! -e kiwi ]; then
  /bin/cp -r 0ne kiwi
fi
if [ ! -e red ]; then
  /bin/cp -r 0ne red
fi

# Serve URI
/bin/rm -rf /srv/www/html/${SITESERVE}.serve
/bin/mkdir -p /srv/www/html/${SITESERVE}.serve/${SERVEDIR}
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${nameURI}\"); die(); ?>" > /srv/www/html/${SITESERVE}.serve/index.php

# Own
/bin/chown -R www:www /srv/www/html
/bin/chmod -R 750 email
/bin/chmod -R 750 one
/bin/chmod -R 750 ink
/bin/chmod -R 750 blue
/bin/chmod -R 750 vip
/bin/chmod -R 750 kiwi
/bin/chmod -R 750 red

# Finish
/bin/echo "Done. Except for any installed apps, any missing Verber html folders have been set to original setup state."
