#!/bin/sh
#inkVerbMaker! verb.ink

# This prepares the early settings for the name286.verb.ink or custom Domain Mod server necessary to make the Verber
## This currently takes no parameters
## This is intended as final prep for the "proper" snapshot image Verbers are created from
### So, it should not be run on "proper" Verber install, but only if from a raw OS image
### This still needs a fresh run of: cd /opt && git clone https://github.com/inkverb/verb
## The basic purpose is to:
### install tools
### set bashrc style
### configure locale

# How to use:
## ./make-verber-preserver


# Directory check
if [ ! -d "/opt/verb" ]; then
/bin/echo "Put the verb directory at /opt/verb first, then try again."
exit 8; fi

# Locale
/usr/bin/cp /etc/locale.gen /etc/locale.gen.orig
/usr/bin/echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
/usr/bin/localectl set-locale LANG=en_US.UTF-8
/usr/bin/locale-gen

# Update
/usr/bin/pacman -Syyu --noconfirm

# Install tools
/usr/bin/pacman -S --noconfirm pwgen zip unzip htop which vim curl wget make cronie gcc autoconf imagemagick git net-tools inetutils man

# Remove unneeded packages
/usr/bin/pacman -Qdt --noconfirm

# Set the prompt style
/opt/verb/serfs/setbashrc
/opt/verb/serfs/setbashrc root

# Vim preferences for root
/bin/echo 'nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p' > /root/.vimrc

# Restart Server and reconnect at the new port
/bin/echo "
Pre-install is finished and is ready to run make-verber.

Run: reboot

Then log back onto the server to run make-verber.
"

# Delete this one-time script
/bin/rm -f /opt/verb/inst/make-verber-preserver
