#!/bin/sh
#inkVerbMaker! verb.ink

# This prepares the early settings for the name286.verb.ink or custom Domain Mod server necessary to make the Verber
## This currently takes no parameters
## This is intended as final prep for the "proper" snapshot image Verbers are created from
### So, it should not be run on "proper" Verber install, but only if from a raw OS image
### This still needs a fresh run of: cd /opt && git clone https://github.com/inkverb/verb
## The basic purpose is to:
### install tools
### set bashrc style
### configure locale

# How to use:
## ./make-verber-preserver


# Directory check
if [ ! -d "/opt/verb" ]; then
/bin/echo "Put the verb directory at /opt/verb first, then try again."
exit 8; fi

# Local
/usr/bin/locale-gen en_US en_US.UTF-8
#dpkg-reconfigure locales # This broke the installer with a dialog
## Set up locality
/bin/echo "LANG="en_US.UTF-8"
LANGUAGE="en_US:en"
LC_ALL="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
" > /etc/default/locale

# Update
/usr/bin/pacman -Syyu --noconfirm

# Install tools
/usr/bin/pacman -S --noconfirm pwgen zip unzip htop which vim curl make cronie gcc autoconf imagemagick git net-tools

# Remove unneeded packages
/usr/bin/pacman -Qdt --noconfirm

# Set the prompt style
/opt/verb/serfs/setbashrc
/opt/verb/serfs/setbashrc root

# Vim preferences for root
/bin/echo 'nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p' > /root/.vimrc

# Restart Server and reconnect at the new port
/bin/echo "
Pre-install is finished and is ready to run make-verber.

Run: reboot

Then log back onto the server to run make-verber.
"

# Delete this one-time script
/bin/rm -f /opt/verb/inst/make-verber-preserver
