#!/bin/bash
#inkVerbMaker! verb.ink
## THIS IS THE BIG ONE! THIS INSTALLS THE NAME AND SETS THE SERVER INTO PRODUCTION ##

# This initially sets the server to the specific namespace at verb.ink etc.
## The SSL email is for registering with Letsencrypt.
## Domains are added to the server after this
## This changes the SSH login port, to keep it the same use 22
## This creates a sudo user with login AND a MySQL superuser by the same name and password
## If using the domain mod (make-dommod), the namespace must be your domain.

# How to use:
## ./setupverb [host] [namespace] [tld] [email] [IT] [serverIPv4] [serverIPv6 - if none use IPv6NA ] [SSLemail] [php.file-limit] [php.up-size] [php.city] [new-port] [new-boss] [boss-pass] [verb-dev - optional]
# Elaborate how to use:
## ./setupverb [host - should be namespace or FQDN tld, unless you want to be strange] [inkVerb namespace (purcha/bin/sed) || Domain Mod domain] [FQDN tld, should be 'ink' except multiple servers for namespace] [email server tld, should be 'email' except multiple servers for namespace] [IT-SQL-FTP server tld, should be 'vip' except multiple servers for namespace] [server IP] [SSL email - used for Letsencrypt and the like] [php file upload limit] [php upload size in MB] [php timezone city] [new port number for ssh/terminal login] [new "boss" sudo user] [boss user password] [verb-update-dev - optional]

# IMPORTANT: Choose a hostname that is: 1. short, 2. unique, 3. memorable, and 4. has only numbers and lower-case letters.
## You will see this name in terminal tabs and window titles when you connect to your Verber via command line.
## Do not choose the same host name on different Verbers of the same namespace, for example ...verb.email and ...verb.ink also need different hosts.
## Consider combining your verb.TLD extension with your Verb namespace
## Eg: joesbigasphalttrucking.verb.ink = joe1ink OR joesbigasphalttrucking.verb.email joeemail

# Timezone list: http://php.net/manual/en/timezones.php
# Common lo/bin/cations:
# Europe/Berlin
# Asia/Hong_Kong
# Asia/Singapore
# America/New_York
# America/Chicago
# America/Phoenix
# America/Los_Angeles

# Eg:
## ./setupverb johnny johnny ink email vip 56.22.108.77 IPv6NA letsencrypt-messages@emaildomain.com 100 1000 Asia/Singapore 22 boss bosspassword
## ./setupverb johnny johnny ink email vip 56.22.108.77 ffff:894:aad8::821 letsencrypt-messages@emaildomain.com 100 1000 Europe/Bucharest 867 boss bosspassword
## ./setupverb johnny2 johnny blue blue blue 56.22.108.77 IPv6NA letsencrypt-messages@emaildomain.com 100 1000 America/New_York 5290 boss bosspassword verb-dev-update
## ./setupverb johnny2 johnny red one kiwi rocks 56.22.108.77 ffff:894:aad8::821 letsencrypt-messages@emaildomain.com 100 1000 America/Phoenix 5290 boss bosspassword verb-dev-update

### Domain Mod:
## ./setupverb itsme inkisaverb.com ink 56.22.108.77 IPv6NA letsencrypt-messages@emaildomain.com 100 1000 America/Detroit 22 boss bosspassword
## ./setupverb itsme inkisaverb.com ink 56.22.108.77 ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff letsencrypt-messages@emaildomain.com 100 1000 America/Detroit 22 boss bosspassword


## PHP timezone can't use third option of state or country such as America/Argentina/San_Juan or America/Indiana/Knox, only such as America/Chicago
## Get PHP timezone list at: http://php.net/manual/en/timezones.php


HNAME="$1"
VNAME="$2"
SERVERTLD="$3"
SVMAILTLD="$4"
ITSQLTLD="$5"
SERVERIPV4="$6"
SERVERIPV6="$7"
SSLEMAIL="$8"
PHPLIMIT="$9"
PHPSIZE="${10}"
PHPCITY="${11}"
NEWPORT="${12}"
NEWBOSS="${13}"
NEWBOSSPASS="${14}"
VUPREPO="${15}"

if [ -z "${15}" ]; then
VUPREPO="verb-dev-update"
fi

if [ -z "${14}" ]; then
/bin/echo "You must set all variables."
exit 8; fi

# Compress IPv6 or set NA to none
compress_ipv6() {
    ip=$1

    blocks=$(/bin/echo $ip | /bin/grep -o "[0-9a-f]\+")
    set $blocks

    # compress leading zeros
    ip=$(printf "%x:%x:%x:%x:%x:%x:%x:%x\n" \
        $(hex2dec $1) \
        $(hex2dec $2) \
        $(hex2dec $3) \
        $(hex2dec $4) \
        $(hex2dec $5) \
        $(hex2dec $6) \
        $(hex2dec $7) \
        $(hex2dec $8)
    )

    # prepend : for easier matching
    ip=:$ip

    # :: must compress the longest chain
    for pattern in :0:0:0:0:0:0:0:0 \
            :0:0:0:0:0:0:0 \
            :0:0:0:0:0:0 \
            :0:0:0:0:0 \
            :0:0:0:0 \
            :0:0; do
        if /bin/echo $ip | /bin/grep -qs $pattern; then
            ip=$(/bin/echo $ip | sed "s/$pattern/::/")
            # if the substitution occured before the end, we have :::
            ip=$(/bin/echo $ip | sed 's/:::/::/')
            break # only one substitution
        fi
    done

    # remove prepending : if necessary
    /bin/echo $ip | /bin/grep -qs "^:[^:]" && ip=$(echo $ip | sed 's/://')

    /bin/echo $ip
}
if [ "${SERVERIPV6}" = "IPv6NA" ]; then
  SERVERIPV6=""
else
  # Call the IP6 compression function just created above
  SERVERIPV6=$(compress_ipv6 ${SERVERIPV6})
fi

# Locale (in case a VPS deleted it after make-verber-preserver)
/usr/bin/localectl set-locale LANG=en_US.UTF-8

# System timezone
/bin/ln -sfn /usr/share/zoneinfo/${PHPCITY} /etc/localtime

# Site settings
## Configs
/usr/bin/mv /opt/verb/inst/mysqlrootpassword /opt/verb/conf/
/usr/bin/mv /opt/verb/conf/sitenameip286 /opt/verb/conf/sitenameip
/usr/bin/mv /opt/verb/conf/siteport286 /opt/verb/conf/siteport
/usr/bin/mv /opt/verb/conf/siteinkget286 /opt/verb/conf/siteinkget
/usr/bin/mv /opt/verb/conf/sitemailpath286 /opt/verb/conf/sitemailpath
/usr/bin/mv /opt/verb/conf/sitetldstatus286 /opt/verb/conf/sitetldstatus
/usr/bin/mv /opt/verb/conf/siteinstallstatus286 /opt/verb/conf/siteinstallstatus
## Ensure scripts are executable
/bin/chmod 750 /opt/verb/serfs/*
/bin/chmod 750 /opt/verb/donjon/*.sh
/bin/chmod 640 /opt/verb/donjon/clamav
/bin/chmod 750 /opt/verb/donjon/repoupdate/*
/bin/chmod 750 /opt/verb/donjon/wpaddsites/*.wpsh

## Domain Mod?
if [ -f "/opt/verb/inst/domain.mod.conf" ]; then
/bin/sed -i "s/name286/\"DOMAIN_MOD-${baseDOM}\"/" /opt/verb/conf/sitenameip
else
/bin/sed -i "s/name286/${VNAME}/" /opt/verb/conf/sitenameip
fi

# Site URI List
## domain.mod?
if [ -f "/opt/verb/inst/domain.mod.conf" ]; then
. /opt/verb/inst/domain.mod.conf
/bin/echo "#!/bin/sh
## This is a config file for other verb scripts
# Site URI List, whether active or not

baseDOM=\"${DMODBASE}\"
emailTLD=\"${SVMAILTLD}\"
itsqlTLD=\"${ITSQLTLD}\"
nameURI=\"${SERVERTLD}.${DMODBASE}\"
hostURI=\"${HNAME}.${SERVERTLD}.${DMODBASE}\"
serveURI=\"serve.${SERVERTLD}.${DMODBASE}\"
emailTLDURI=\"${SVMAILTLD}.${DMODBASE}\"
itsqlTLDURI=\"${ITSQLTLD}.${DMODBASE}\"
emailURI=\"email.${DMODBASE}\"
oneURI=\"one.${DMODBASE}\"
inkURI=\"ink.${DMODBASE}\"
blueURI=\"blue.${DMODBASE}\"
vipURI=\"vip.${DMODBASE}\"
kiwiURI=\"kiwi.${DMODBASE}\"
redURI=\"red.${DMODBASE}\"
" > /opt/verb/conf/siteurilist
## Normal verb domains
else
/bin/echo "#!/bin/sh
## This is a config file for other verb scripts
# Site URI List, whether they are active or not

emailTLD=\"${SVMAILTLD}\"
itsqlTLD=\"${ITSQLTLD}\"
nameURI=\"${VNAME}.verb.${SERVERTLD}\"
hostURI=\"${HNAME}.${VNAME}.verb.${SERVERTLD}\"
serveURI=\"serve.${VNAME}.verb.${SERVERTLD}\"
emailTLDURI=\"${VNAME}.verb.${SVMAILTLD}\"
itsqlTLDURI=\"${VNAME}.verb.${ITSQLTLD}\"
emailURI=\"${VNAME}.verb.email\"
oneURI=\"${VNAME}.verb.one\"
inkURI=\"${VNAME}.verb.ink\"
blueURI=\"${VNAME}.verb.blue\"
vipURI=\"${VNAME}.verb.vip\"
kiwiURI=\"${VNAME}.verb.kiwi\"
redURI=\"${VNAME}.verb.red\"
" > /opt/verb/conf/siteurilist
fi
. /opt/verb/conf/siteurilist

# Snakeoil cert (larger file for production)
/usr/bin/mkdir -p /etc/ssl/server
cd /etc/ssl/server
/usr/bin/rm -f server.key
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out server.key
/usr/bin/chmod 400 server.key
/usr/bin/rm -f server.csr
country="na"
state="na"
locality="na"
organization="${nameURI}"
organizationalunit="IT"
commonname="${nameURI}"
email="snakeoil@${nameURI}"
companyname="${nameURI}"
/usr/bin/openssl req -new -sha256 -key server.key -out server.csr \
    -subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email/unstructuredName=$companyname/"
/usr/bin/openssl x509 -req -days 3650 -in server.csr -signkey server.key -out server.crt
/usr/bin/rm -f server.csr

## Diffie-Helman Group file (larger file for production)
/usr/bin/rm -f /etc/ssl/server/dhparams.pem
#/usr/bin/openssl dhparam -out /etc/ssl/server/dhparams.pem 4096
/usr/bin/openssl dhparam -out /etc/ssl/server/dhparams.pem 2048
/bin/chmod 600 /etc/ssl/server/dhparams.pem
cd $OLDPWD

# Site name & IP
serveDIR="$(/usr/bin/pwgen -s -1 6)"
/bin/sed -i "s/host286/${HNAME}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/tld286/${SERVERTLD}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/tldserve286/${SERVERTLD}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/servedir286/${serveDIR}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/serveuri286/${serveURI}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/ip286/${SERVERIPV4}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/ipv6286/${SERVERIPV6}/" /opt/verb/conf/sitenameip
/bin/sed -i "s:timecity286:${PHPCITY}:" /opt/verb/conf/sitenameip
/bin/sed -i "s/updaterepo286/${VUPREPO}/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITEEMAILTLD=.*/SITEEMAILTLD=\"${SVMAILTLD}\"/" /opt/verb/conf/sitemailpath
/bin/sed -i "s/inkcertemail286/${SSLEMAIL}/" /opt/verb/conf/inkcert/inkcertstatus
## Copy other config files with pre-install status
/usr/bin/mv /opt/verb/conf/sitemailpass286 /opt/verb/conf/sitemailpass
/usr/bin/mv /opt/verb/conf/siteufwip286 /opt/verb/conf/siteufwip

# LAEMP Reverse Proxy?
if [ -f "/etc/httpd/conf/rpaf.conf" ]; then
  /bin/sed -i "s/ip286/${SERVERIPV4}/g" /etc/httpd/conf/rpaf.conf
  /bin/sed -i "s/ipv6286/${SERVERIPV6}/g" /etc/httpd/conf/rpaf.conf
fi

# PHP ini file
/usr/bin/mv /opt/verb/conf/php.name286.ini /opt/verb/conf/php.${VNAME}.ini
/bin/sed -i "s/phplimit286/${PHPLIMIT}/g" /opt/verb/conf/php.${VNAME}.ini
/bin/sed -i "s/phpsize286M/${PHPSIZE}M/g" /opt/verb/conf/php.${VNAME}.ini
/bin/sed -i "s:phptimecity286:${PHPCITY}:g" /opt/verb/conf/php.${VNAME}.ini
/bin/sed -i "s/name286/${VNAME}/g" /opt/verb/conf/php.${VNAME}.ini
/bin/sed -i "s/;.*.open_basedir =.*/open_basedir = \/var\/www/" /opt/verb/conf/php."${VNAME}".ini
/bin/sed -i "s/;.*.sys_temp_dir =.*/sys_temp_dir = \/var\/www\/tmp/" /opt/verb/conf/php."${VNAME}".ini
/bin/sed -i "s/;.*.upload_tmp_dir =.*/upload_tmp_dir = \/var\/www\/tmp/" /opt/verb/conf/php."${VNAME}".ini

# Get the current PHP version & set php.ini
/usr/bin/mv /etc/php/php.ini /etc/php/php.original.ini
/bin/ln -sfn /opt/verb/conf/php.${VNAME}.ini /etc/php/php.ini
/bin/chmod 644 /etc/php/php.ini

# sites-available
. /opt/verb/conf/servertype
## Apache
if [ -d "/opt/verb/conf/webserver/httpd/sites-available" ]; then
  ### Replace
  /bin/sed -i "s/emailTLD286/${emailTLD}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/itsqlTLD286/${itsqlTLD}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/itsqlTLDURI286/${itsqlTLDURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/emailURI286/${emailURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/inkURI286/${inkURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/blueURI286/${blueURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/kiwiURI286/${kiwiURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  /bin/sed -i "s/redURI286/${redURI}/g" /opt/verb/conf/webserver/httpd/sites-available/*.conf
  ### Rename
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*emailTLDURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%emailTLDURI286.conf/}${emailTLDURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*itsqlTLDURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%itsqlTLDURI286.conf/}${itsqlTLDURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*emailURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%emailURI286.conf/}${emailURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*oneURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%oneURI286.conf/}${oneURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*inkURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%inkURI286.conf/}${inkURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*blueURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%blueURI286.conf/}${blueURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*vipURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%vipURI286.conf/}${vipURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*kiwiURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%kiwiURI286.conf/}${kiwiURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/httpd/sites-available/*redURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%redURI286.conf/}${redURI}.conf"
  done
fi
## Nginx
if [ -d "/opt/verb/conf/webserver/nginx/sites-available" ]; then
  ### Replace
  /bin/sed -i "s/emailTLD286/${emailTLD}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/itsqlTLD286/${itsqlTLD}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/itsqlTLDURI286/${itsqlTLDURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/emailURI286/${emailURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/inkURI286/${inkURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/blueURI286/${blueURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/kiwiURI286/${kiwiURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  /bin/sed -i "s/redURI286/${redURI}/g" /opt/verb/conf/webserver/nginx/sites-available/*.conf
  ### Rename
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*emailTLDURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%emailTLDURI286.conf/}${emailTLDURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*itsqlTLDURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%itsqlTLDURI286.conf/}${itsqlTLDURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*emailURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%emailURI286.conf/}${emailURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*oneURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%oneURI286.conf/}${oneURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*inkURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%inkURI286.conf/}${inkURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*blueURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%blueURI286.conf/}${blueURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*vipURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%vipURI286.conf/}${vipURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*kiwiURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%kiwiURI286.conf/}${kiwiURI}.conf"
  done
  for cfg in /opt/verb/conf/webserver/nginx/sites-available/*redURI286.conf
  do
    /usr/bin/mv -- "$cfg" "${cfg/%redURI286.conf/}${redURI}.conf"
  done
fi

# New site-files
## Directories
/bin/chmod -R 750 /opt/verb/conf/site-files/newdomain.tld
/bin/chmod -R 750 /opt/verb/conf/site-files/newvipsubdir
/bin/chmod -R 750 /opt/verb/conf/site-files/newonesubdir
## Replace
/bin/sed -i "s/emailTLD286/${emailTLD}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/itsqlTLD286/${itsqlTLD}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/itsqlTLDURI286/${itsqlTLDURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/emailURI286/${emailURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/inkURI286/${inkURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/blueURI286/${blueURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/kiwiURI286/${kiwiURI}/g" /opt/verb/conf/site-files/conf/*
/bin/sed -i "s/redURI286/${redURI}/g" /opt/verb/conf/site-files/conf/*

# inkCert ini and cron files
## Replace
/bin/sed -i "s/sslemail286/${SSLEMAIL}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkcert/verber-openssl.cnf
/bin/sed -i "s/emailURI286/${emailURI}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/inkURI286/${inkURI}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/blueURI286/${blueURI}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/kiwiURI286/${kiwiURI}/g" /opt/verb/conf/inkcert/cli-ini/*
/bin/sed -i "s/redURI286/${redURI}/g" /opt/verb/conf/inkcert/cli-ini/*
## Rename
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.emailURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${emailURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.oneURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${oneURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.inkURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${inkURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.blueURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${blueURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.vipURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${vipURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.kiwiURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${kiwiURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/cli.redURI286.ini /opt/verb/conf/inkcert/cli-ini/cli.${redURI}.ini
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.emailURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${emailURI}
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.oneURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${oneURI}
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.inkURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.blueURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${blueURI}
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.vipURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${vipURI}
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.kiwiURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${kiwiURI}
/usr/bin/mv /opt/verb/conf/inkcert/cli-ini/siteinkcert.redURI286 /opt/verb/conf/inkcert/cli-ini/siteinkcert.${redURI}

# www default indexes
/opt/verb/serfs/updatehtmlverbs; wait

# Link sites
if [ -d "/opt/verb/conf/webserver/httpd/sites-available" ] && [ -d "/etc/httpd" ]; then
  /bin/ln -sfn /opt/verb/conf/webserver/httpd/sites-available /etc/httpd/
  /bin/ln -sfn /opt/verb/conf/webserver/httpd/sites-enabled /etc/httpd/
fi
if [ -d "/opt/verb/conf/webserver/nginx/sites-available" ] && [ -d "/etc/nginx" ]; then
  /bin/ln -sfn /opt/verb/conf/webserver/nginx/sites-available /etc/nginx/
  /bin/ln -sfn /opt/verb/conf/webserver/nginx/sites-enabled /etc/nginx/
fi

# inkCert mail subdomains
/opt/verb/serfs/setinkcertmailsubdomains ${nameURI}

# inkCert email web server subdomains for RoundCube and PostfixAdmin
/bin/sed -i "s/, pfa.${emailTLDURI}//g" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
/bin/sed -i "s/, rc.${emailTLDURI}//g" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
/bin/sed -i "/^domains =/ s/$/, pfa.${emailTLDURI}, rc.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini

# inkCert email web server subdomains for RoundCube and PostfixAdmin
/bin/sed -i "s/, sql.${itsqlTLDURI}//g" /opt/verb/conf/inkcert/cli-ini/cli.${itsqlTLDURI}.ini
/bin/sed -i "/^domains =/ s/$/, sql.${itsqlTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${itsqlTLDURI}.ini

# Enable sites
. /opt/verb/conf/sitetldstatus
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx pfa.${emailTLDURI} rc.${emailTLDURI}
fi
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx sql.${itsqlTLDURI}
fi
if [ ${VERBemail} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${emailURI} e.${emailURI}
fi
if [ ${VERBone} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${oneURI} o.${oneURI}
fi
if [ ${VERBink} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${inkURI} i.${inkURI}
fi
if [ ${VERBblue} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${blueURI} b.${blueURI}
fi
if [ ${VERBvip} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${vipURI} v.${vipURI}
fi
if [ ${VERBkiwi} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${kiwiURI} k.${kiwiURI}
fi
if [ ${VERBred} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensitenginx ${redURI} r.${redURI}
fi
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /bin/systemctl restart nginx; wait
fi
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache pfa.${emailTLDURI} rc.${emailTLDURI}
fi
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then
  /opt/verb/serfs/ensiteapache sql.${itsqlTLDURI}
fi
if [ ${VERBemail} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${emailURI} e.${emailURI}
fi
if [ ${VERBone} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${oneURI} o.${oneURI}
fi
if [ ${VERBink} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${inkURI} i.${inkURI}
fi
if [ ${VERBblue} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${blueURI} b.${blueURI}
fi
if [ ${VERBvip} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${vipURI} v.${vipURI}
fi
if [ ${VERBkiwi} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${kiwiURI} k.${kiwiURI}
fi
if [ ${VERBred} = "true" ] && [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /opt/verb/serfs/ensiteapache ${redURI} r.${redURI}
fi
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /bin/systemctl restart httpd; wait
fi

# Serve URI
/opt/verb/serfs/setserve

# Create the new boss user
/usr/bin/groupadd ${NEWBOSS}
/usr/bin/useradd -g ${NEWBOSS} ${NEWBOSS}
/bin/echo "${NEWBOSS}:${NEWBOSSPASS}" | chpasswd
/usr/bin/usermod -a -G sudo ${NEWBOSS}
/usr/bin/usermod -a -G www ${NEWBOSS}
/usr/bin/mkdir -p /home/${NEWBOSS}
/bin/ln -sfn /opt/verb/boss /home/${NEWBOSS}/
## User privilege specifi/bin/cation
/bin/echo "${NEWBOSS}  ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/${NEWBOSS}
## Vim preferences
echo 'nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p' > /home/${NEWBOSS}/.vimrc
## BASH settings
/opt/verb/serfs/setbashrc ${NEWBOSS}
## Own
/usr/bin/chown -R ${NEWBOSS}:${NEWBOSS} /home/${NEWBOSS}

# New Boss MySQL root password
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE USER ${NEWBOSS}@localhost;
SET PASSWORD FOR ${NEWBOSS}@localhost=PASSWORD('${NEWBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO '${NEWBOSS}'@'localhost' IDENTIFIED BY '${NEWBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Host name

/usr/bin/hostnamectl set-hostname ${HNAME}
##DEV this restart causes an "is masked" error and may not be necessary with the mandatory reboot after setupverb
#/bin/systemctl restart hostname
## Set /etc/hostname
/bin/echo "${hostURI}" > /etc/hostname
## Set /etc/hosts
/usr/bin/cat <<EOF > /etc/hosts
# inkVerb IPv4
127.0.1.1 ${hostURI} ${HNAME}
${SERVERIPV4} ${hostURI} ${HNAME}
::1 localhost
127.0.0.1 localhost.localdomain localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

## inkVerb IPv6 ##
${SERVERIPV6} ${hostURI} ${HNAME}
EOF

# ARPA & inverse IP
/opt/verb/serfs/setip4 "${SERVERIPV4}"
/opt/verb/serfs/setip6 "${SERVERIPV6}"

# Verber DNS records
## Include config
. /opt/verb/conf/sitenameip

## Set the FQDN host
/bin/echo "
; FQDN Host Records
${hostURI}.	IN  A		hostip286
${hostURI}.	IN  AAAA	hostipv6286" >> /opt/verb/conf/inkdns/inkzones/db.${SITETLD}
/bin/echo "
; FQDN PTR Host Records
hostarpaip286  IN  PTR  ${hostURI}.
hostarpaipv6286  IN  PTR  ${hostURI}." >> /opt/verb/conf/inkdns/inkzones/nv.${SITETLD}

## Set the email TLD URI
/bin/echo "
; Email Control Records" >> /opt/verb/conf/inkdns/inkzones/db.${SVMAILTLD}
/bin/echo "
; Email Control PTR Records" >> /opt/verb/conf/inkdns/inkzones/nv.${SVMAILTLD}

## Set the itsql TLD URI
/bin/echo "
; IT Control Records
sql.${itsqlTLDURI}.	IN  A		hostip286
sql.${itsqlTLDURI}.	IN  AAAA	hostipv6286" >> /opt/verb/conf/inkdns/inkzones/db.${ITSQLTLD}
/bin/echo "
; IT Control PTR Records
hostarpaip286  IN  PTR  sql.${itsqlTLDURI}.
hostarpaipv6286  IN  PTR  sql.${itsqlTLDURI}." >> /opt/verb/conf/inkdns/inkzones/nv.${ITSQLTLD}

## Set the namespace, TLD, and IP values
/usr/bin/mkdir -p /opt/verb/conf/inkdns/zones
/bin/sed -i "s/hostip286/${SERVERIPV4}/g" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s/hostip286/${SERVERIPV4}/g" /opt/verb/conf/inkdns/db.dnsdomain
/bin/sed -i "s/hostipv6286/${SERVERIPV6}/g" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s/hostipv6286/${SERVERIPV6}/g" /opt/verb/conf/inkdns/db.dnsdomain
/bin/sed -i "s/sitename286/${SITENAME}/g" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s/sitename286/${SITENAME}/g" /opt/verb/conf/inkdns/db.dnsdomain
/bin/sed -i "s/sitetld286/${SITETLD}/g" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s/sitetld286/${SITETLD}/g" /opt/verb/conf/inkdns/db.dnsdomain
/bin/sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkdns/db.dnsdomain
/bin/sed -i "s/mailURI286/${nameURI}/g" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s/mailURI286/${nameURI}/g" /opt/verb/conf/inkdns/db.dnsdomain

### nv.*
/bin/sed -i "s/hostarpaip286/${SITEARPAIP4}/g" /opt/verb/conf/inkdns/inkzones/nv.*
/bin/sed -i "s/hostarpaip286/${SITEARPAIP4}/g" /opt/verb/conf/inkdns/nv.dnsdomain
/bin/sed -i "s/hostarpaipv6286/${SITEARPAIP6}/g" /opt/verb/conf/inkdns/inkzones/nv.*
/bin/sed -i "s/hostarpaipv6286/${SITEARPAIP6}/g" /opt/verb/conf/inkdns/nv.dnsdomain

## Populate the Verber domains
/bin/sed -i "s/hostdomain286/${emailURI}/g" /opt/verb/conf/inkdns/inkzones/db.email
/bin/sed -i "s/hostdomain286/${oneURI}/g" /opt/verb/conf/inkdns/inkzones/db.one
/bin/sed -i "s/hostdomain286/${inkURI}/g" /opt/verb/conf/inkdns/inkzones/db.ink
/bin/sed -i "s/hostdomain286/${blueURI}/g" /opt/verb/conf/inkdns/inkzones/db.blue
/bin/sed -i "s/hostdomain286/${vipURI}/g" /opt/verb/conf/inkdns/inkzones/db.vip
/bin/sed -i "s/hostdomain286/${kiwiURI}/g" /opt/verb/conf/inkdns/inkzones/db.kiwi
/bin/sed -i "s/hostdomain286/${redURI}/g" /opt/verb/conf/inkdns/inkzones/db.red
/bin/sed -i "s/hostdomain286/${emailURI}/g" /opt/verb/conf/inkdns/inkzones/nv.email
/bin/sed -i "s/hostdomain286/${oneURI}/g" /opt/verb/conf/inkdns/inkzones/nv.one
/bin/sed -i "s/hostdomain286/${inkURI}/g" /opt/verb/conf/inkdns/inkzones/nv.ink
/bin/sed -i "s/hostdomain286/${blueURI}/g" /opt/verb/conf/inkdns/inkzones/nv.blue
/bin/sed -i "s/hostdomain286/${vipURI}/g" /opt/verb/conf/inkdns/inkzones/nv.vip
/bin/sed -i "s/hostdomain286/${kiwiURI}/g" /opt/verb/conf/inkdns/inkzones/nv.kiwi
/bin/sed -i "s/hostdomain286/${redURI}/g" /opt/verb/conf/inkdns/inkzones/nv.red
## Set host FQDN
/bin/sed -i "s/;; End Root Site Defaults/${hostURI}\.\t\tIN  A\t\t${SERVERIPV4}\n${hostURI}\.\t\tIN  AAAA\t${SERVERIPV6}\n;; End Root Site Defaults/" /opt/verb/conf/inkdns/inkzones/db.${SERVERTLD}
## Set the URI names
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.email /opt/verb/conf/inkdns/inkzones/db.${emailURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.one /opt/verb/conf/inkdns/inkzones/db.${oneURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.ink /opt/verb/conf/inkdns/inkzones/db.${inkURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.blue /opt/verb/conf/inkdns/inkzones/db.${blueURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.vip /opt/verb/conf/inkdns/inkzones/db.${vipURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.kiwi /opt/verb/conf/inkdns/inkzones/db.${kiwiURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/db.red /opt/verb/conf/inkdns/inkzones/db.${redURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.email /opt/verb/conf/inkdns/inkzones/nv.${emailURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.one /opt/verb/conf/inkdns/inkzones/nv.${oneURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.ink /opt/verb/conf/inkdns/inkzones/nv.${inkURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.blue /opt/verb/conf/inkdns/inkzones/nv.${blueURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.vip /opt/verb/conf/inkdns/inkzones/nv.${vipURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.kiwi /opt/verb/conf/inkdns/inkzones/nv.${kiwiURI}
/usr/bin/mv /opt/verb/conf/inkdns/inkzones/nv.red /opt/verb/conf/inkdns/inkzones/nv.${redURI}
## Serial Nos
cd /opt/verb/conf/inkdns/inkzones
for inkZoneDB in db.*; do
inkZone="$(/bin/echo ${inkZoneDB} | /bin/sed 's/db\.//' )"
/opt/verb/serfs/inkdnsserial ${inkZone} verber
done
cd $OLDPWD

## Set for IPV6 (should be set already, but just to be sure)
/bin/sed -i "s/IPV6=.*/IPV6=yes/" /etc/default/ufw
## Port (set to something to avoid attacks)
/bin/sed -i "/Port.*/ c\Port ${NEWPORT}" /etc/ssh/sshd_config
/bin/sed -i "/SITEPORT.*/ c\SITEPORT=${NEWPORT}" /opt/verb/conf/siteport
/usr/bin/ufw allow ${NEWPORT}
/usr/bin/ufw --force enable; wait
## Reset settings
#/usr/bin/ufw allow ssh
#/usr/bin/ufw allow http
#/usr/bin/ufw allow https
#/usr/bin/ufw allow ftp
#/usr/bin/ufw allow sftp

# Security check
/opt/verb/serfs/setsecure; wait

# Instructions
######################### FIX inkCert instructions #########################
/bin/echo "After reboot:
1. Turn off any unused verb domains and change the email server if you choose
2. Install:
  - inkDNS (inkdnsinstall)
  - inkVmail (inkvmailinstall)
  - inkCert (inkcertinstall; inkcertdole-all-verbs)

First, you must reboot the server now using:

reboot

Then for SSH,
login root: 'ssh root@${SERVERIPV4} -p ${NEWPORT}'
login boss: 'ssh ${NEWBOSS}@${SERVERIPV4} -p ${NEWPORT}'
"

# Cleanup
#/usr/bin/ufw --force enable # Delete if everything works
/usr/bin/rm -f /opt/verb/serfs/setupverb
/usr/bin/rm -rf /opt/verb/inst
/bin/systemctl reload sshd; wait
